### PR TITLE
feat: support Tampa GTFS

### PR DESCRIPTION
**Pull request by BumbleFlash**
PR to add model classes to support Tampa Model classes

### CODE REVIEW

**Comment by BumbleFlash** [comment]
@barbeau I have updated the box folder with Tampa's OSM and GTFS data. I'm not able to find a link to Tampa's HOPR GBFS feed. I came across an issue you opened a year back (https://github.com/NABSA/gbfs/issues/149), is this why I'm not able to find the feed?

**Comment by barbeau** [comment]
This should be HOPR Tampa feed:
https://gbfs.hopr.city/api/gbfs/8/

**Comment by BumbleFlash** [comment]
Thanks! I have added the new `router-config.json` to the box folder with the HOPR and spin GBFS feed. I can add the tests for Tampa's API once we get this merged.

**Review by barbeau — APPROVED** [review]
Thanks @BumbleFlash!

**Comment by barbeau** [comment]
@BumbleFlash In the Box folder could you also please add a very simple README with the instructions to start the server using those files too?

**Pull request merged**
