### PR TITLE
ci: Test commit to see if the main branch fails on macOS

### PR DESCRIPTION
**Pull request by barbeau**
**Please do NOT merge**

This is a test to see if the main branch fails when running on macOS on CI, for troubleshooting the CI failure in https://github.com/CUTR-at-USF/opentripplanner-client-library/pull/12 after merging changes from #13.

### CODE REVIEW

**Comment by BumbleFlash** [comment]
@barbeau Let me try doing this here https://github.com/CUTR-at-USF/opentripplanner-client-library/pull/12#issuecomment-815961091

**Comment by barbeau** [comment]
@BumbleFlash Sounds good - thanks!

**Comment by BumbleFlash** [comment]
Booyah!

**Comment by barbeau** [comment]
PR https://github.com/CUTR-at-USF/opentripplanner-client-library/pull/12 is fixed, so we can close this.

**Pull request closed without merging**
